spring:
  datasource:
    url: jdbc:h2:file:./db/spring-data-jpa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 6000

